apiVersion: v1
kind: Service
metadata:
  name: github-api
spec:
  selector:
    app: github-api
  ports:
  - port: 3000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-api
  labels:
    app: github-api
spec:
  selector:
    matchLabels:
      app: github-api
  replicas: 1
  template:
    metadata:
      labels:
        app: github-api
    spec:
      containers:
      - name: github-api
        image: containerlocation/github-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: DISABLE_WEB_APP
          value: "false"
